### ISSUE TITLE
32-bit sunset on macOS

### ISSUE THREAD

**Issue by sjml** [increpare/bfxr#17]
Currently, starting bxfr on macOS mojave (10.14) gives a warning about it needing to be updated for future releases (as they sunset 32-bit support). 

I realize (a) this is probably a limitation of the Adobe AIR runtime and (b) this likely isn't a super high priority project, but is there any chance of a repackaging to work with 64-bit systems? 

Thanks for your great work on this!

**Comment by increpare** [comment]
Cobbled together a new build.  Does this fix it:

http://ded.increpare.com/~locus/bfxr_update/Bfxr_MAC.zip 

?

**Comment by sjml** [comment]
Looks good! Thanks so much! Glad to be able to keep using this tool. :)

**Comment by increpare** [comment]
Thanks so much for confirming :)  Should keep it running for another few years...
