### ISSUE TITLE
MacOS version not compatible with MacOS Catalina

### ISSUE THREAD

**Issue by AppleJax5** [increpare/bfxr#19]
32bit binaries are not supported on the newest release of MacOS. To be able to run bfxr on MacOS 10.14 (and newer) a 64bit binary is required.

**Comment by increpare** [comment]
the new version should have 64 bit binaries.  have you downloaded from the website lately?  ( updated it over the  summer)

**Comment by AppleJax5** [comment]
The newer version is working fine. I did download it aczually but I accidentally mixed something up.
Anyway, great software, good work. Thanks!
