### ISSUE TITLE
[feature request] allow direct input of parameters

### ISSUE THREAD

**Issue by Gnumaru** [increpare/bfxr#25]
It would be nice if the parameters could also be input manually in a text field instead of only via sliders.

The text field could be anywhere in the parameter line, like between the parameter name and the respective slider.

Sliders are very user friendly, but direct input appeals to users that want to know what the parameters are numerically (which currently can only be known while clicking and holding the slider picker) and want a finer control. It could also yield a faster workflow for changing parameters. Imagine the following use case:

1. The user clicks the text field for the first parameter
1. The user types a value numeric value and press enter. Since the parameter changed, the sound is played. The application automatically selects the entire text in the input so that it can be overwritten more easily
1. The user didn't like the sound. Since all the text in the input is already selected, he just types a new value and presses enter. If the text where not selected, the user would need to type ctrl+A to select all text before typing a new value to overwrite the old one
1. The user still didn't like the sound. He types a new value and presses enter. The previous application behavior is repeated.
1. The user did like the outcome. Then he presses tab three times so that the focus jumps from the input text to the slider, then to the lock icon in the next parameter, then the input text field in the next parameter.
1. The user continues manually fiddling with each parameter until achieving the desired final result.

Currently, since there is no text field, the user would have to press the right or left arrow several times while focusing the slider picker in order to achieve a desired result, which needs more effort than trying to type a value. While typing a value, the user can do binary partitioning in the numeric range to search for a better value which is much harder to do on a slider. Eg.: suppose the numeric range is between 0 and 1. The user inputs 0 and don't like the result, then input 1 and don't like also, then input 0.5 and also dislikes, but thinks a higher value would be better. Then the user inputs .7, then .9, then .8, then .85, then .83 and finally he gets to the better result he could get. With only a slider, the user would have to drag to 0, then to 1, then to .5 and from that point on the user would probably just keep pressing the right arrow until achieving the desired result.

**Comment by increpare** [comment]
Thanks for the suggestion.  I'm ok with the functionality as it is (not just for my use-cases, but in general for others).  Accessibility wise it might be better to have numerical input as an option.  But yeah, overall I'm ok with it as is.  [also the software is very difficult for me to change now - I no longer have a license to the compiler used to compile it...]
