### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by guzuligo** [increpare/bfxr#3]
Can you help? I want a kind of hello world code to start using this please.

Regards,

**Comment by increpare** [comment]
go to http://bfxr.net/ and hit randomize over and over.  there are tooltips
over each of the sliders, if you want to know what they do.

**Comment by guzuligo** [comment]
I am talking about the as3 code, not the wave generator. I want to start using the functions to generate sfx. This way, my SFX won't increase the file size even if I have thousands of them.

**Comment by increpare** [comment]
There's an api example here :
https://github.com/increpare/bfxr-api-example

it might be a bit out of date from the main branch, but should be ok for
most things.

Peace,

S
